name: Generate GitHub Contributions Snake

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install platane/snk@v3

      - name: Generate images and GIF
        run: |
          npx snk generate \
            --github_user_name="${{ github.repository_owner }}" \
            --outputs="dist/github-snake.svg,dist/github-snake-dark.svg?palette=github-dark,dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"
